receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"
  
  syslog:
    tcp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc5424
    location: UTC
    operators:
      - type: move
        from: attributes.message
        to: body
        mapping:
          severity: attributes.severity
          facility: attributes.facility
          version: attributes.version
          timestamp: attributes.timestamp
          hostname: attributes.host
          appname: attributes.app
          procid: attributes.proc_id
          msgid: attributes.msg_id
          structured_data: attributes.structured_data

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  
  prometheus:
    endpoint: "0.0.0.0:8889"

extensions:
  health_check:
  pprof:
    endpoint: "0.0.0.0:1777"
  zpages:
    endpoint: "0.0.0.0:55679"

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    
    logs:
      receivers: [otlp, syslog]  # Including syslog receiver for logs
      processors: [batch]
      exporters: [debug]

  telemetry:
    logs:
      level: "debug"
    metrics:
      address: "0.0.0.0:8888"
