services:
  demo-syslog-sender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - otel-collector
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demoSyslog
      SPRING_DATASOURCE_PASSWORD: root123
      SPRING_DATASOURCE_USERNAME: postgres
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_SERVICE_NAME: demo-syslog-sender
    networks:
      - otel-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: demoSyslog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/collector/otel-collector-config.yml"]
    volumes:
      - ./docker/collector/otel-collector-config.yml:/etc/collector/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      # - "54526:54526" # Syslog TCP
      - "8888:8888"   # Metrics endpoint
      # - "8889:8889"   # Prometheus endpoint
      - "1777:1777"   # pprof extension
      - "55679:55679" # zpages extension
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge

volumes:
  pgdata: